public with sharing class MeetingsController {

    public String createMeetings(String data) {
        return '{}';
    }

    public String updateMeetings(String data) {
        return '{}';
    }

    public String addUsers(String data) {
        return '{}';
    }

    public String removeUsers(String data) {
        return '{}';
    }

    public String getMeetingList(String data) {
        return '{}';
    }

    public String sendInvite(String data) {
        return '{}';
    }
}
